-- Retention is enforced by the history application service using the configured
-- 30-day policy and an injected Clock. The schema stores only the safe response
-- snapshot; the raw request is intentionally not represented by any column.

CREATE TABLE scan_history (
    scan_id UUID PRIMARY KEY,
    redacted_display_value VARCHAR(2048) NOT NULL,
    scheme VARCHAR(5) NOT NULL,
    host VARCHAR(512) NOT NULL,
    ascii_host VARCHAR(253) NOT NULL,
    registrable_domain VARCHAR(253),
    port INTEGER,
    path VARCHAR(2048) NOT NULL,
    query_present BOOLEAN NOT NULL,
    fragment_present BOOLEAN NOT NULL,
    score INTEGER NOT NULL,
    risk_level VARCHAR(16) NOT NULL,
    engine_version VARCHAR(128) NOT NULL,
    analyzed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT scan_history_scheme_check CHECK (scheme IN ('http', 'https')),
    CONSTRAINT scan_history_port_check CHECK (port IS NULL OR (port >= 0 AND port <= 65535)),
    CONSTRAINT scan_history_score_check CHECK (score >= 0 AND score <= 100),
    CONSTRAINT scan_history_risk_level_check CHECK (risk_level IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL'))
);

CREATE INDEX scan_history_analyzed_at_idx ON scan_history (analyzed_at);

CREATE TABLE scan_history_finding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id UUID NOT NULL,
    finding_position INTEGER NOT NULL,
    rule_id VARCHAR(64) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    points INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    explanation VARCHAR(2048) NOT NULL,
    evidence VARCHAR(2048),
    CONSTRAINT scan_history_finding_scan_fk
        FOREIGN KEY (scan_id) REFERENCES scan_history (scan_id) ON DELETE CASCADE,
    CONSTRAINT scan_history_finding_position_check CHECK (finding_position >= 0),
    CONSTRAINT scan_history_finding_severity_check CHECK (severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT scan_history_finding_points_check CHECK (points >= 0),
    CONSTRAINT scan_history_finding_order_uq UNIQUE (scan_id, finding_position)
);

CREATE INDEX scan_history_finding_scan_position_idx
    ON scan_history_finding (scan_id, finding_position);
